# Generated by Django 3.1.6 on 2021-05-13 18:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commentingOn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.comment'),
        ),
        migrations.CreateModel(
            name='Subcomments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=200)),
                ('likes', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.comment')),
            ],
        ),
    ]
