# Generated by Django 3.1.6 on 2021-05-13 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20210513_1125'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subcomments',
        ),
    ]
